pull_request_template.md

add: docs(pull_request_template)

---

index.html
src/Pages/LoginPage.tsx
src/Pages/MainPage.tsx

변경 사항
- 지도 api 위치 & root display 수정
- loginpage 작성 중

style(MainPage.tsx): Map, root style

---

src/PageRouter.tsx
src/Pages/ViewPage.tsx
src/Pages/WritePage.tsx

feat: ViewPage.tsx

---

index.html
src/Pages/LoginPage.tsx
src/Pages/MyPage.tsx
src/Pages/MyPageEditPage.tsx
src/Pages/MyPageLikeListPage.tsx
src/Pages/MyhashtagPage.tsx
src/Pages/SingupDetailPage.tsx

feat: MyPage, MyPageEditPage

---

src/PageRouter.tsx
src/Pages/MyPage.tsx
src/Pages/MyPageLikeListPage.tsx
src/Pages/MyhashtagPage.tsx

feat: MyhashtagPage

---

src/Footer/Footer.tsx
src/PageRouter.tsx
src/Pages/SearchPage.tsx

Search page

---

src/PageRouter.tsx
src/Pages/AlarmPage.tsx

feat: AlarmPage

---

src/Pages/MyPage.tsx
src/Pages/MyPageLikeListPage.tsx
src/Pages/MyhashtagPage.tsx

feat: MyPageLikeListPage

---

src/Footer/Footer.tsx

feat: route map

---

src/PageRouter.tsx
src/Pages/MyPage.tsx
src/Pages/MyPageLikeListPage.tsx
src/Pages/ReviewErranderPage.tsx
src/Pages/ReviewSolverPage.tsx

fix: MyPage 탈퇴하기 버튼 추가

---

src/Pages/ReviewErranderPage/ReviewErranderPage.tsx
src/Pages/ReviewErranderPage/styled.ts
src/Pages/ReviewSolverPage/ReviewSolverPage.tsx
src/Pages/ReviewSolverPage/styled.ts

feat: ReviewErranderPage, ReviewSolverPage

---

src/Pages/MainPage/MainPage.tsx
src/Pages/MainPage/MapComponent.tsx
src/Pages/MainPage/styled.ts
src/Pages/ReviewErranderPage/styled.ts
src/Pages/ReviewSolverPage/styled.ts

docs: MainPage, MainComponents로 분리

---

src/Pages/SignpDetailPage/MapComponent.tsx
src/Pages/SignpDetailPage/SingupDetailPage.tsx
src/Pages/SignpDetailPage/styled.ts

dosc: SinpupDetailPage, MapComponent로 분리

---

src/PageRouter.tsx
src/Pages/SignpDetailPage/SignupDetailPage.tsx
src/Pages/SignupPage/SignupPage.tsx

docs: signup 수정

---

src/Pages/LoginPage/kakao/kakaoLoginData.ts

refactor: signup 오타, redirect_url 테스트를 위해 수정

---

src/Footer/Footer.tsx
src/Header/Header.tsx
src/Pages/LoginPage/kakao/kakaoLoginData.ts
src/Pages/Mypage/MyPage.tsx
src/Pages/Mypage/styled.ts
src/Pages/SignpDetailPage/SignupDetailPage.tsx

feat: kakao 로그아웃 기능 구현

---

src/Pages/WritePage/WritePage.tsx
src/Pages/WritePage/styled.ts

feat: image delete button

---

src/Pages/LoginPage/LoginPage.tsx
src/Pages/LoginPage/kakao/kakaoLoginData.ts
src/Pages/MyPageEditPage/MyPageEditPage.tsx
src/Pages/MyPageEditPage/styled.ts
src/Pages/Mypage/MyPage.tsx
src/Pages/Mypage/styled.ts

feat: kakao 탈퇴 기능

---

src/Header/Header.tsx
src/Pages/Mypage/MyPage.tsx
src/Pages/Mypage/styled.ts

feat: mypage LocationSetingBtn 등록

---

package-lock.json
package.json
src/Pages/WritePage/WritePage.tsx

Drag image

---

src/Pages/WritePage/WritePage.tsx
src/Pages/WritePage/styled.ts

feat: hashTag CRUD

---

src/Pages/SignpDetailPage/SignupDetailPage.tsx

fix: react-daum-postcode 수정

---

src/Pages/MyPageEditPage/MyPageEditPage.tsx
src/Pages/MyPageEditPage/styled.ts

feat: MyPageEditPage의 프로필 사진 변경, 삭제 기능

---

package-lock.json
package.json
src/Header/Header.tsx
src/Pages/LoginPage/LoginPage.tsx
src/Pages/SignpDetailPage/SignupDetailPage.tsx
vite.config.ts

refactor: vite 환경변수 이름 수정

---

src/Pages/SearchPage/SearchPage.tsx
src/Pages/SearchPage/searchPageAPI.json
src/Pages/SearchPage/styled.ts

feat: search with hashtag

---

src/Pages/SearchPage/SearchPage.tsx

hotfix: search with title & hashtag

---

src/PageRouter.tsx
src/Pages/LocationPage/LocationPage.tsx
src/Pages/LocationPage/styled.ts
src/Pages/Mypage/MyPage.tsx
src/Pages/SignpDetailPage/SignupDetailPage.tsx
src/Pages/SignpDetailPage/styled.ts

feat: LocationPage 구현

---

.env

test: 배포를 위한 REDIRECT_URI 변경

---

.env

test: REDIRECT_URI 주소 변경

---

src/Pages/SignpDetailPage/SignupDetailPage.tsx
src/Pages/SignupPage/SignupPage.tsx

style: textColor 삭제

---

index.html
src/Footer/Footer.tsx
src/PageRouter.tsx
src/Pages/ChattingListPage/ChattingListPage.tsx
src/Pages/ChattingListPage/styled.ts
src/Pages/ChattingPage/ChattingPage.tsx
src/Pages/ChattingPage/styled.ts
src/Pages/ChattingProfilePage/ChattingProfilePage.tsx
src/Pages/ChattingProfilePage/styled.ts

feat: ChattingListPage 레이아웃

---

src/Pages/ChattingListPage/ChattingListPage.tsx
src/Pages/ChattingPage/ChattingPage.tsx
src/Pages/ChattingPage/styled.ts

feat: ChattingPage 레이아웃

---

src/PageRouter.tsx
src/Pages/ChattingPage/ChattingPage.tsx
src/Pages/ChattingProfilePage/ChattingProfilePage.tsx
src/Pages/ChattingProfilePage/styled.ts

feat: ChattingProfilePage 레이아웃

---

db.json
package-lock.json
package.json
src/Pages/SearchPage/SearchPage.tsx
src/Pages/WritePage/WritePage.tsx
src/Pages/WritePage/styled.ts

[feat]: Write data & search data

---

src/Pages/MyhashtagPage/MyhashtagPage.tsx

feat: MyhashtagPage 엔터 키 등록

---

src/PageRouter.tsx
src/Pages/MyReviewPage/MyReviewPage.tsx
src/Pages/MyReviewPage/styled.ts
src/Pages/Mypage/MyPage.tsx
src/Pages/Mypage/styled.ts

feat: MyReviewPage 레이아웃

---

db.json
src/Pages/MyPageEditPage/MyPageEditPage.tsx
src/Pages/Mypage/MyPage.tsx
src/Pages/Mypage/styled.ts

feat: 닉네임 수정 기능(json-sever)

---

db.json
src/Pages/MyPageEditPage/MyPageEditPage.tsx
src/Pages/Mypage/MyPage.tsx

fix: json-sever 주소

---

src/Pages/ChattingPage/ChattingPage.tsx
src/Pages/ChattingPage/styled.ts
src/Pages/ChattingProfilePage/ChattingProfilePage.tsx
src/Pages/ChattingProfilePage/styled.ts
src/Pages/LocationPage/LocationPage.tsx
src/Pages/LocationPage/styled.ts
src/Pages/MyPageEditPage/MyPageEditPage.tsx
src/Pages/MyPageEditPage/styled.ts
src/Pages/MyPageLikeListPage/MyPageLikeListPage.tsx
src/Pages/MyPageLikeListPage/styled.ts
src/Pages/MyReviewPage/MyReviewPage.tsx
src/Pages/MyReviewPage/styled.ts
src/Pages/MyhashtagPage/MyhashtagPage.tsx
src/Pages/MyhashtagPage/styled.ts

feat: 뒤로 가기 버튼 추가

---

src/Pages/LoginPage/LoginPage.tsx
src/Pages/Mypage/MyPage.tsx
src/Pages/SignpDetailPage/SignupDetailPage.tsx
src/Pages/SignupPage/SignupPage.tsx
src/Pages/SignupPage/styled.ts
vite.config.ts

feat: 일반 로그인 api 연동 (회원가입, 로그인)

---

src/Pages/API/axiosAPI.tsx
src/Pages/LocationPage/LocationPage.tsx
src/Pages/LoginPage/LoginPage.tsx
src/Pages/MainPage/MainPage.tsx
src/Pages/MyPageEditPage/MyPageEditPage.tsx
src/Pages/Mypage/MyPage.tsx
src/Pages/Mypage/styled.ts
src/Pages/SignpDetailPage/SignupDetailPage.tsx
src/Pages/SignpDetailPage/styled.ts
src/Pages/SignupPage/SignupPage.tsx

feat: 닉네임 수정, 도로명주소 수정 (axios instance 사용)

---

.github/workflows/deploy.yaml
db.json
package-lock.json
src/Header/Header.tsx
src/PageRouter.tsx
src/Pages/LocationPage/LocationPage.tsx
src/Pages/LoginPage/LoginPage.tsx
src/Pages/MainPage/MapComponent.tsx
src/Pages/SignpDetailPage/SignupDetailPage.tsx
src/Pages/ViewPage/ViewPage.tsx
vite.config.ts

GitHub secrets

---

.github/workflows/deploy.yaml
db.json
package-lock.json
src/Header/Header.tsx
src/PageRouter.tsx
src/Pages/LocationPage/LocationPage.tsx
src/Pages/LoginPage/LoginPage.tsx
src/Pages/MainPage/MainPage.tsx
src/Pages/MainPage/MapComponent.tsx
src/Pages/MyPageEditPage/MyPageEditPage.tsx
src/Pages/SignpDetailPage/SignupDetailPage.tsx
src/Pages/ViewPage/ViewPage.tsx
vite.config.ts

fix: mainpage - getuser 오류 수정

---

index.html
src/Pages/MainPage/MainPage.tsx
src/Pages/MainPage/MapComponent.tsx

saveMarkers

---

db.json
src/Pages/MainPage/MainPage.tsx
src/Pages/MainPage/MapComponent.tsx
src/Pages/MainPage/withinDistance.ts

calculateDistance

---

package-lock.json
src/Pages/WritePage/WritePage.tsx
src/Pages/WritePage/styled.ts

[edit]: styled변수명 수정

---

db.json
src/Pages/MainPage/MapComponent.tsx
src/Pages/MainPage/customOverlay.css
src/Pages/MainPage/styled.ts
src/Pages/WritePage/WritePage.tsx

feat: 마커 오버레이 클릭 구현

---

src/Pages/WritePage/WritePage.tsx

feat: 글자수 , 본문 글자 수 ,가격 설정 제한

---

db.json
src/Pages/MainPage/MainPage.tsx
src/Pages/MainPage/MapComponent.tsx
src/Pages/SearchPage/SearchPage.tsx
src/Pages/ViewPage/ViewPage.tsx
src/Pages/WritePage/WritePage.tsx
src/recoil/atoms.tsx

feat: nickname recoil State

---

db.json
src/Pages/MainPage/MapComponent.tsx
src/Pages/SearchPage/SearchPage.tsx
src/Pages/ViewPage/ViewPage.tsx
src/Pages/WritePage/WritePage.tsx

feat: nickname recoil state 확인

---

src/Pages/SearchPage/SearchPage.tsx
src/Pages/ViewPage/ViewPage.tsx

fix: viewPage 템플릿 리터럴 로직 수정 searchPage 비동기 로직 수정

---

src/Pages/API/axiosAPI.tsx
src/Pages/MainPage/MainPage.tsx
src/Pages/ViewPage/ViewPage.tsx
src/recoil/atoms.tsx

feat: click like

---

src/Pages/API/axiosAPI.tsx
src/Pages/MyPageLikeListPage/MyPageLikeListPage.tsx
src/Pages/MyPageLikeListPage/styled.ts
src/Pages/WritePage/WritePage.tsx
src/recoil/atoms.tsx

feat: 의뢰 post 기능 성공! ✨

---

src/Pages/WritePage/WritePage.tsx

fix: writePage레이아웃 / 테스트 완료

---

src/PageRouter.tsx
src/Pages/SearchPage/SearchPage.tsx
src/Pages/ViewPage/ViewPage.tsx
src/Pages/WritePage/SetLocationPage.tsx
src/Pages/WritePage/WritePage.tsx
src/Pages/WritePage/styled.ts

feat: set dead line

---

src/Pages/MyPageLikeListPage/MyPageLikeListPage.tsx
src/Pages/MyPageLikeListPage/styled.ts
src/Pages/MyReviewPage/MyReviewPage.tsx
src/Pages/MyhashtagPage/MyhashtagPage.tsx

Refactor: mypage hashtag, review 로직

---

src/Pages/MyPageEditPage/MyPageEditPage.tsx
src/Pages/MyPageEditPage/styled.ts

feat: 프로필 이미지 수정 기능

---

index.html
src/PageRouter.tsx
src/Pages/API/axiosAPI.tsx
src/Pages/WritePage/SetLocation.tsx
src/Pages/WritePage/SetLocationPage.tsx
src/Pages/WritePage/WritePage.tsx
src/Pages/WritePage/styled.ts
src/recoil/atoms.tsx

feat: 중앙 좌표 주소로 변환

---

src/Pages/WritePage/SetLocation.tsx
src/Pages/WritePage/WritePage.tsx

feat: location post request

---

src/Pages/WritePage/SetLocation.tsx

fix: url, method, headers 수정

---

src/Pages/SearchPage/SearchPage.tsx

fix: searchPage 요청 url 및 데이터 수정

---

src/Pages/ReviewSolverPage/ReviewSolverPage.tsx

fix: 평가페이지에서 서버로 넘어가는 key값 수정2

---

src/Pages/MyPageLikeListPage/MyPageLikeListPage.tsx
src/Pages/MyPageLikeListPage/styled.ts
src/Pages/ViewPage/ViewPage.tsx

feat: 관심글 등록, 의뢰 좋아요 기능 합침

---

src/Pages/MainPage/MapComponent.tsx
src/Pages/SearchPage/SearchPage.tsx
src/Pages/ViewPage/ViewPage.tsx
src/Pages/WritePage/WritePage.tsx

fix: 메인 페이지 의뢰 조회 기능 수정

---

src/Pages/MainPage/MainPage.tsx
src/Pages/MainPage/MapComponent.tsx

fix: login상태에서만 지도를 볼 수 있게 설정

---

src/Pages/MainPage/MapComponent.tsx
src/Pages/SearchPage/SearchPage.tsx
src/Pages/WritePage/SetLocation.tsx
src/Pages/WritePage/WritePage.tsx

feat: hashtag, deadline 연동 추가

---

src/Pages/ViewPage/ViewPage.tsx
src/Pages/ViewPage/styled.ts
src/Pages/WritePage/WritePage.tsx

fix: 캐러셀 버그 수정

---

src/Pages/ViewPage/ViewPage.tsx

fix: 조회수 수정

---

index.html
package-lock.json
package.json
src/Pages/ChattingPage/ChattingPage.tsx
src/Pages/SearchPage/SearchPage.tsx
src/Pages/ViewPage/ViewPage.tsx

fix: 좋아요 실시간 반영

---

src/Pages/ViewPage/styled.ts
src/Pages/WritePage/styled.ts

fix: WritePage, ViewPage css

---

src/Header/Header.tsx
src/Pages/SearchPage/SearchPage.tsx
src/Pages/SearchPage/styled.ts
src/Pages/ViewPage/ViewPage.tsx

fix: profiledata 추가

---

src/Footer/Footer.tsx
src/Header/Header.tsx
src/PageRouter.tsx
src/Pages/ChattingPage/ChattingPage.tsx
src/Pages/MainPage/MapComponent.tsx
src/Pages/MyReviewPage/MyReviewPage.tsx
src/Pages/ReviewSolverPage/ReviewSolverPage.tsx
src/Pages/SolverPage/SolverPage.tsx
src/Pages/SolverPage/styled.ts
src/Pages/ViewPage/ViewPage.tsx
src/Pages/WritePage/SetLocation.tsx
src/Pages/WritePage/WritePage.tsx

final: 배포용
